environments:
    - name: prod
      configs:
          endpoints:
              production:
                  url: 'https://petstore.swagger.io/v2/'
              sandbox:
                  url: 'https://petstore.swagger.io/v2/'
          deploymentEnvironments:
              - displayOnDevportal: true
                deploymentEnvironment: Default
                deploymentVhost: localhost
